# Comparing boroughs of different cities

# 1. Introduction and Business Problem

For persons who move from one city to another, it could be useful to compare different boroughs of different cities for them to pick the borough that correpsonds the best to what they were used to. We would take an example of New York and Toronto.

# 2. Data Analysis

In [174]:
#importing libraries

import requests
import pandas as pd
from pandas import json_normalize
import json 
import numpy as np 
from geopy.geocoders import Nominatim 
import folium 
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
from scipy.spatial import distance 
from sklearn.cluster import KMeans
import matplotlib.cm as cm
import matplotlib.colors as colors
print('Libraries imported.')

Libraries imported.

### Part I. Analysing New York data set

In [175]:
# The code was removed by Watson Studio for sharing.

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (18,19,20,22,23,24,26,63,64,76,79,86) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,borough,block,lot,cd,ct2010,cb2010,schooldist,council,zipcode,firecomp,policeprct,healthcenterdistrict,healtharea,sanitboro,sanitdistrict,sanitsub,address,zonedist1,zonedist2,zonedist3,zonedist4,overlay1,overlay2,spdist1,spdist2,spdist3,ltdheight,splitzone,bldgclass,landuse,easements,ownertype,ownername,lotarea,bldgarea,comarea,resarea,officearea,retailarea,garagearea,strgearea,factryarea,otherarea,areasource,numbldgs,numfloors,unitsres,unitstotal,lotfront,lotdepth,bldgfront,bldgdepth,ext,proxcode,irrlotcode,lottype,bsmtcode,assessland,assesstot,exempttot,yearbuilt,yearalter1,yearalter2,histdist,landmark,builtfar,residfar,commfar,facilfar,borocode,bbl,condono,tract2010,xcoord,ycoord,zonemap,zmcode,sanborn,taxmap,edesignum,appbbl,appdate,plutomapid,firm07_flag,pfirm15_flag,version,dcpedited,latitude,longitude,notes
0,SI,1701,96,501.0,303.02,4004.0,31.0,49.0,10303.0,E166,121.0,51.0,100.0,5.0,1.0,4C,HEATHER COURT,R3-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,Z7,NaN,0.0,X,WOODMONT WEST HOA INC,3900.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0.0,0.0,0.0,0.0,30.00,130.00,0.00,0.00,N,0.0,N,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.00,0.50,0.0,1.0,5,5.017010e+09,NaN,30302.0,941123.0,166666.0,20d,NaN,500 000,50702.0,NaN,5.017010e+09,01/02/1992,1,NaN,NaN,21v1,NaN,40.624031,-74.155358,NaN
1,MN,16,7502,101.0,317.04,2000.0,2.0,1.0,10280.0,E010,1.0,15.0,8900.0,1.0,1.0,1A,320 ALBANY STREET,BPC,NaN,NaN,NaN,NaN,NaN,BPC,NaN,NaN,NaN,N,R4,3.0,0.0,X,HUDSON TOWER,27838.0,123284.0,11136.0,112148.0,0.0,0.0,10690.0,0.0,0.0,446.0,2.0,1.0,15.0,133.0,135.0,287.38,100.50,287.00,100.00,NaN,0.0,Y,5.0,5.0,3560406.0,18347862.0,18347862.0,1986.0,0.0,0.0,NaN,NaN,4.43,0.00,0.0,0.0,1,1.000168e+09,313.0,31704.0,979379.0,197988.0,12b,NaN,101S090,10101.0,NaN,1.000162e+09,08/25/1988,1,1.0,1.0,21v1,NaN,40.710107,-74.017570,NaN
2,MN,348,46,103.0,14.02,2001.0,1.0,1.0,10002.0,L018,7.0,14.0,7400.0,1.0,3.0,2A,80 CLINTON STREET,R7A,NaN,NaN,NaN,C1-5,NaN,NaN,NaN,NaN,NaN,N,K4,4.0,0.0,NaN,JANE ARDSLEY FROCKS INC,12870.0,31314.0,19314.0,12000.0,4500.0,4500.0,0.0,10314.0,0.0,0.0,2.0,2.0,5.0,8.0,10.0,50.17,200.67,50.17,200.67,N,0.0,Y,4.0,0.0,466650.0,1958400.0,0.0,1910.0,0.0,0.0,NaN,NaN,2.43,4.00,0.0,4.0,1,1.003480e+09,NaN,1402.0,988459.0,201070.0,12c,NaN,101N080,10201.0,E-216,NaN,NaN,1,NaN,NaN,21v1,NaN,40.718566,-73.984816,NaN
3,MN,2241,25,112.0,295.00,4002.0,6.0,10.0,10034.0,E095,34.0,17.0,120.0,1.0,12.0,4B,4915 BROADWAY,R7-2,NaN,NaN,NaN,C2-4,NaN,IN,NaN,NaN,NaN,N,D7,4.0,0.0,NaN,4915 BROADWAY REALTYLLC,30000.0,107085.0,12000.0,95085.0,8000.0,4000.0,0.0,0.0,0.0,0.0,2.0,1.0,6.0,94.0,100.0,200.00,150.00,200.00,123.00,N,2.0,N,5.0,1.0,445950.0,3799350.0,0.0,1936.0,0.0,0.0,NaN,NaN,3.57,3.44,0.0,6.5,1,1.022410e+09,NaN,295.0,1005747.0,255410.0,3a,NaN,112 057,10804.0,NaN,NaN,NaN,1,NaN,NaN,21v1,NaN,40.867690,-73.922277,NaN
4,BK,3234,13,304.0,423.00,3001.0,32.0,37.0,11221.0,E218,83.0,34.0,3200.0,3.0,4.0,1A,684 HART STREET,R6,NaN,NaN,NaN,C1-3,NaN,NaN,NaN,NaN,NaN,N,C0,2.0,0.0,NaN,"VARGAS, MERCED",1500.0,2700.0,0.0,2700.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,3.0,3.0,20.00,75.00,20.00,45.00,N,3.0,N,5.0,2.0,9120.0,82800.0,0.0,1901.0,0.0,0.0,NaN,NaN,1.80,2.43,0.0,4.8,3,3.032340e+09,NaN,423.0,1004926.0,193908.0,13b,NaN,309 012,31103.0,NaN,NaN,NaN,1,NaN,NaN,21v1,NaN,40.698885,-73.925434,NaN

In [176]:
#cleaning the data set

NY_df = df_data_3[['borough', 'latitude', 'longitude']]
NY_df.head()

  borough   latitude  longitude
0      SI  40.624031 -74.155358
1      MN  40.710107 -74.017570
2      MN  40.718566 -73.984816
3      MN  40.867690 -73.922277
4      BK  40.698885 -73.925434

In [177]:
#counting the boroughs

print("There are a total of " +str(len(NY_df["borough"].unique())) +" unique Boroughs in New York")
NY_df["borough"].unique()
NY_df.groupby(["borough"]).count().reset_index()

There are a total of 5 unique Boroughs in New York

  borough  latitude  longitude
0      BK    276581     276581
1      BX     89601      89601
2      MN     42431      42431
3      QN    324397     324397
4      SI    124853     124853

In [179]:
#establishing NY coordinates using geolocator

NY_address = 'New York City, NY'

NY_geolocator = Nominatim(user_agent="ny_explorer")
NY_location = NY_geolocator.geocode(NY_address)
NY_latitude = NY_location.latitude
NY_longitude = NY_location.longitude
print('New York s coordinates are {}, {}.'.format(NY_latitude, NY_longitude))

New York s coordinates are 40.7127281, -74.0060152.

In [180]:
#entering Foursquare credentials

CLIENT_ID = '5JAXSZRX035SR2MBU3J3GHQY1EF0ZD5VVENVEY3UJ4OFO0U0'
CLIENT_SECRET = 'G2B5HMMHBEVQ5QI2JDWXYFAG1U5I4NAA11KVNQBVSFC05GZG' 
ACCESS_TOKEN = 'VA0SECL4SPWWSDVJFMIJMEWRRRTKKCMX1XDDL0KUAF4OLISQ'
VERSION = '20180604'
LIMIT = 30
RADIUS = 500
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    NY_latitude, 
    NY_longitude,
    VERSION, 
    RADIUS, 
    LIMIT)
NY_results = requests.get(url).json()
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 5JAXSZRX035SR2MBU3J3GHQY1EF0ZD5VVENVEY3UJ4OFO0U0
CLIENT_SECRET:G2B5HMMHBEVQ5QI2JDWXYFAG1U5I4NAA11KVNQBVSFC05GZG

In [181]:
#exploring NY using Foursquare

def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [183]:
venues = NY_results['response']['venues']   
NY_places = json_normalize(venues)
filtered_columns = ['name', 'categories', 'location.lat', 'location.lng']
NY_places = NY_places.loc[:, filtered_columns]
NY_places['categories'] = NY_places.apply(get_category_type, axis=1)
NY_places.columns = [col.split(".")[-1] for col in NY_places.columns]
NY_places.head()

KeyError: 'venues'

In [ ]:
print("There are "+ str(len(ny_venues["categories"].unique()))+" unique venue categories and "+ str(ny_venues["name"].count()) +" venues in New York City")

In [ ]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
            
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [ ]:
NY_places = getNearbyVenues(names=NY_df['borough'],
                                   latitudes=NY_df['latitude'],
                                   longitudes=NY_df['longitude']
                                  )

In [ ]:
print(NY_places.shape)
print("There are a total of "+ str(len(ny_venues["Venue Category"].unique()))+" unique venue categories and "+ str(NY_places["Venue"].count()) +" venues in New York City")
NY_places.head()

### Part II. Analysing Toronto data set

In [189]:
source = requests.get("https://web.archive.org/web/20190825081918/https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M").text
soup = BeautifulSoup(source, 'lxml')

table = soup.find("table")
table_rows = table.tbody.find_all("tr")

res = []
for tr in table_rows:
    td = tr.find_all("td")
    row = [tr.text for tr in td]
    
    if row != [] and row[1] != "Not assigned":
        if "Not assigned" in row[2]: 
            row[2] = row[1]
        res.append(row)

T_df = pd.DataFrame(res, columns = ["PostalCode", "Borough", "Neighborhood"])
T_df.head()

  PostalCode           Borough        Neighborhood
0        M3A        North York         Parkwoods\n
1        M4A        North York  Victoria Village\n
2        M5A  Downtown Toronto      Harbourfront\n
3        M5A  Downtown Toronto       Regent Park\n
4        M6A        North York  Lawrence Heights\n

In [190]:
T_df["Neighborhood"] = T_df["Neighborhood" ].str.replace("\n","")
T_df["Borough"] = T_df["Borough" ].str.replace("\n","")
T_df["PostalCode"] = T_df["PostalCode" ].str.replace("\n","")
T_df = T_df.groupby(["PostalCode", "Borough"])["Neighborhood"].apply(", ".join).reset_index()
print("Shape: ", T_df.shape)
T_df.head()

Shape:  (103, 3)

  PostalCode      Borough                            Neighborhood
0        M1B  Scarborough                          Rouge, Malvern
1        M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough       Guildwood, Morningside, West Hill
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae

In [191]:
df_coordinates = pd.read_csv('https://cocl.us/Geospatial_data')

In [192]:
df_coordinates.head(100)

   Postal Code   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
5          M1J  43.744734 -79.239476
6          M1K  43.727929 -79.262029
7          M1L  43.711112 -79.284577
8          M1M  43.716316 -79.239476
9          M1N  43.692657 -79.264848
10         M1P  43.757410 -79.273304
11         M1R  43.750072 -79.295849
12         M1S  43.794200 -79.262029
13         M1T  43.781638 -79.304302
14         M1V  43.815252 -79.284577
15         M1W  43.799525 -79.318389
16         M1X  43.836125 -79.205636
17         M2H  43.803762 -79.363452
18         M2J  43.778517 -79.346556
19         M2K  43.786947 -79.385975
20         M2L  43.757490 -79.374714
21         M2M  43.789053 -79.408493
22         M2N  43.770120 -79.408493
23         M2P  43.752758 -79.400049
24         M2R  43.782736 -79.442259
25         M3A  43.753259 -79.329656
26         M3B  43.745906 -79.352188
27         M3C  43.725900 -79.340923
28         M3H  43.754328 -79.442259
29         M3J  43.767980 -79.487262
30         M3K  43.737473 -79.464763
31         M3L  43.739015 -79.506944
32         M3M  43.728496 -79.495697
33         M3N  43.761631 -79.520999
34         M4A  43.725882 -79.315572
35         M4B  43.706397 -79.309937
36         M4C  43.695344 -79.318389
37         M4E  43.676357 -79.293031
38         M4G  43.709060 -79.363452
39         M4H  43.705369 -79.349372
40         M4J  43.685347 -79.338106
41         M4K  43.679557 -79.352188
42         M4L  43.668999 -79.315572
43         M4M  43.659526 -79.340923
44         M4N  43.728020 -79.388790
45         M4P  43.712751 -79.390197
46         M4R  43.715383 -79.405678
47         M4S  43.704324 -79.388790
48         M4T  43.689574 -79.383160
49         M4V  43.686412 -79.400049
50         M4W  43.679563 -79.377529
51         M4X  43.667967 -79.367675
52         M4Y  43.665860 -79.383160
53         M5A  43.654260 -79.360636
54         M5B  43.657162 -79.378937
55         M5C  43.651494 -79.375418
56         M5E  43.644771 -79.373306
57         M5G  43.657952 -79.387383
58         M5H  43.650571 -79.384568
59         M5J  43.640816 -79.381752
60         M5K  43.647177 -79.381576
61         M5L  43.648198 -79.379817
62         M5M  43.733283 -79.419750
63         M5N  43.711695 -79.416936
64         M5P  43.696948 -79.411307
65         M5R  43.672710 -79.405678
66         M5S  43.662696 -79.400049
67         M5T  43.653206 -79.400049
68         M5V  43.628947 -79.394420
69         M5W  43.646435 -79.374846
70         M5X  43.648429 -79.382280
71         M6A  43.718518 -79.464763
72         M6B  43.709577 -79.445073
73         M6C  43.693781 -79.428191
74         M6E  43.689026 -79.453512
75         M6G  43.669542 -79.422564
76         M6H  43.669005 -79.442259
77         M6J  43.647927 -79.419750
78         M6K  43.636847 -79.428191
79         M6L  43.713756 -79.490074
80         M6M  43.691116 -79.476013
81         M6N  43.673185 -79.487262
82         M6P  43.661608 -79.464763
83         M6R  43.648960 -79.456325
84         M6S  43.651571 -79.484450
85         M7A  43.662301 -79.389494
86         M7R  43.636966 -79.615819
87         M7Y  43.662744 -79.321558
88         M8V  43.605647 -79.501321
89         M8W  43.602414 -79.543484
90         M8X  43.653654 -79.506944
91         M8Y  43.636258 -79.498509
92         M8Z  43.628841 -79.520999
93         M9A  43.667856 -79.532242
94         M9B  43.650943 -79.554724
95         M9C  43.643515 -79.577201
96         M9L  43.756303 -79.565963
97         M9M  43.724766 -79.532242
98         M9N  43.706876 -79.518188
99         M9P  43.696319 -79.532242

In [193]:
T_df = pd.merge(T_df, df_coordinates, how='left', left_on = 'PostalCode', right_on = 'Postal Code')
T_df.head(100)

,PostalCode,Borough,Neighborhood,Postal Code,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",M1B,43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",M1C,43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",M1E,43.763573,-79.188711
3,M1G,Scarborough,Woburn,M1G,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,M1H,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,M1J,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",M1K,43.727929,-79.262029
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge",M1L,43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",M1M,43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",M1N,43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ...",M1P,43.757410,-79.273304
11,M1R,Scarborough,"Maryvale, Wexford",M1R,43.750072,-79.295849
12,M1S,Scarborough,Agincourt,M1S,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter",M1T,43.781638,-79.304302
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St...",M1V,43.815252,-79.284577
15,M1W,Scarborough,L'Amoreaux West,M1W,43.799525,-79.318389
16,M1X,Scarborough,Upper Rouge,M1X,43.836125,-79.205636
17,M2H,North York,Hillcrest Village,M2H,43.803762,-79.363452
18,M2J,North York,"Fairview, Henry Farm, Oriole",M2J,43.778517,-79.346556
19,M2K,North York,Bayview Village,M2K,43.786947,-79.385975
20,M2L,North York,"Silver Hills, York Mills",M2L,43.757490,-79.374714
21,M2M,North York,"Newtonbrook, Willowdale",M2M,43.789053,-79.408493
22,M2N,North York,Willowdale South,M2N,43.770120,-79.408493
23,M2P,North York,York Mills West,M2P,43.752758,-79.400049
24,M2R,North York,Willowdale West,M2R,43.782736,-79.442259
25,M3A,North York,Parkwoods,M3A,43.753259,-79.329656
26,M3B,North York,Don Mills North,M3B,43.745906,-79.352188
27,M3C,North York,"Flemingdon Park, Don Mills South",M3C,43.725900,-79.340923
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights",M3H,43.754328,-79.442259
29,M3J,North York,"Northwood Park, York University",M3J,43.767980,-79.487262
30,M3K,North York,"CFB Toronto, Downsview East",M3K,43.737473,-79.464763
31,M3L,North York,Downsview West,M3L,43.739015,-79.506944
32,M3M,North York,Downsview Central,M3M,43.728496,-79.495697
33,M3N,North York,Downsview Northwest,M3N,43.761631,-79.520999
34,M4A,North York,Victoria Village,M4A,43.725882,-79.315572
35,M4B,East York,"Woodbine Gardens, Parkview Hill",M4B,43.706397,-79.309937
36,M4C,East York,Woodbine Heights,M4C,43.695344,-79.318389
37,M4E,East Toronto,The Beaches,M4E,43.676357,-79.293031
38,M4G,East York,Leaside,M4G,43.709060,-79.363452
39,M4H,East York,Thorncliffe Park,M4H,43.705369,-79.349372
40,M4J,East York,East Toronto,M4J,43.685347,-79.338106
41,M4K,East Toronto,"The Danforth West, Riverdale",M4K,43.679557,-79.352188
42,M4L,East Toronto,"The Beaches West, India Bazaar",M4L,43.668999,-79.315572
43,M4M,East Toronto,Studio District,M4M,43.659526,-79.340923
44,M4N,Central Toronto,Lawrence Park,M4N,43.728020,-79.388790
45,M4P,Central Toronto,Davisville North,M4P,43.712751,-79.390197
46,M4R,Central Toronto,North Toronto West,M4R,43.715383,-79.405678
47,M4S,Central Toronto,Davisville,M4S,43.704324,-79.388790
48,M4T,Central Toronto,"Moore Park, Summerhill East",M4T,43.689574,-79.383160
49,M4V,Central Toronto,"Deer Park, Forest Hill SE, Rathnelly, South Hi...",M4V,43.686412,-79.400049
50,M4W,Downtown Toronto,Rosedale,M4W,43.679563,-79.377529
51,M4X,Downtown Toronto,"Cabbagetown, St. James Town",M4X,43.667967,-79.367675
52,M4Y,Downtown Toronto,Church and Wellesley,M4Y,43.665860,-79.383160
53,M5A,Downtown Toronto,"Harbourfront, Regent Park",M5A,43.654260,-79.360636
54,M5B,Downtown Toronto,"Ryerson, Garden District",M5B,43.657162,-79.378937
55,M5C,Downtown Toronto,St. James Town,M5C,43.651494,-79.375418
56,M5E,Downtown Toronto,Berczy Park,M5E,43.644771,-79.373306
57,M5G,Downtown Toronto,Central Bay Street,M5G,43.657952,-79.387383
58,M5H,Downtown Toronto,"Adelaide, King, Richmond",M5H,43.650571,-79.384568
59,M5J,Downtown Toronto,"Harbourfront East, Toronto Islands, Union Station",M5J,43.640816,-79.381752
60,M5K,Downtown Toronto,"Design Exchange, Toronto Dominion Centre",M5K,43.647177,-79.381576
61,M5L,Downtown Toronto,"Commerce Court, Victoria Hotel",M5L,43.648198,-79.379817
62,M5M,North York,"Bedford Park, Lawrence Manor East",M5M,43.733283,-79.419750
63,M5N,Central Toronto,Roselawn,M5N,43.711695,-79.416936
64,M5P,Central Toronto,"Forest Hill North, Forest Hill West",M5P,43.696948,-79.411307
65,M5R,Central Toronto,"The Annex, North Midtown, Yorkville",M5R,43.672710,-79.405678
66,M5S,Downtown Toronto,"Harbord, University of Toronto",M5S,43.662696,-79.400049
67,M5T,Downtown Toronto,"Chinatown, Grange Park, Kensington Market",M5T,43.653206,-79.400049
68,M5V,Downtown Toronto,"CN Tower, Bathurst Quay, Island airport, Harbo...",M5V,43.628947,-79.394420
69,M5W,Downtown Toronto,Stn A PO Boxes 25 The Esplanade,M5W,43.646435,-79.374846
70,M5X,Downtown Toronto,"First Canadian Place, Underground city",M5X,43.648429,-79.382280
71,M6A,North York,"Lawrence Heights, Lawrence Manor",M6A,43.718518,-79.464763
72,M6B,North York,Glencairn,M6B,43.709577,-79.445073
73,M6C,York,Humewood-Cedarvale,M6C,43.693781,-79.428191
74,M6E,York,Caledonia-Fairbanks,M6E,43.689026,-79.453512
75,M6G,Downtown Toronto,Christie,M6G,43.669542,-79.422564
76,M6H,West Toronto,"Dovercourt Village, Dufferin",M6H,43.669005,-79.442259
77,M6J,West Toronto,"Little Portugal, Trinity",M6J,43.647927,-79.419750
78,M6K,West Toronto,"Brockton, Exhibition Place, Parkdale Village",M6K,43.636847,-79.428191
79,M6L,North York,"Downsview, North Park, Upwood Park",M6L,43.713756,-79.490074
80,M6M,York,"Del Ray, Keelesdale, Mount Dennis, Silverthorn",M6M,43.691116,-79.476013
81,M6N,York,"The Junction North, Runnymede",M6N,43.673185,-79.487262
82,M6P,West Toronto,"High Park, The Junction South",M6P,43.661608,-79.464763
83,M6R,West Toronto,"Parkdale, Roncesvalles",M6R,43.648960,-79.456325
84,M6S,West Toronto,"Runnymede, Swansea",M6S,43.651571,-79.484450
85,M7A,Queen's Park,Queen's Park,M7A,43.662301,-79.389494
86,M7R,Mississauga,Canada Post Gateway Processing Centre,M7R,43.636966,-79.615819
87,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern,M7Y,43.662744,-79.321558
88,M8V,Etobicoke,"Humber Bay Shores, Mimico South, New Toronto",M8V,43.605647,-79.501321
89,M8W,Etobicoke,"Alderwood, Long Branch",M8W,43.602414,-79.543484
90,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",M8X,43.653654,-79.506944
91,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So...",M8Y,43.636258,-79.498509
92,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen...",M8Z,43.628841,-79.520999
93,M9A,Etobicoke,Islington Avenue,M9A,43.667856,-79.532242
94,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ...",M9B,43.650943,-79.554724
95,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol...",M9C,43.643515,-79.577201
96,M9L,North York,Humber Summit,M9L,43.756303,-79.565963
97,M9M,North York,"Emery, Humberlea",M9M,43.724766,-79.532242
98,M9N,York,Weston,M9N,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,M9P,43.696319,-79.532242

In [194]:
T_address = "Toronto, ON"

T_geolocator = Nominatim(user_agent="toronto_explorer")
T_location = T_geolocator.geocode(T_address)
T_latitude = T_location.latitude
T_longitude = T_location.longitude
print('The geograpical coordinate of Toronto are {}, {}.'.format(T_latitude, T_longitude))

The geograpical coordinate of Toronto are 43.6534817, -79.3839347.

In [195]:
CLIENT_ID = '5JAXSZRX035SR2MBU3J3GHQY1EF0ZD5VVENVEY3UJ4OFO0U0'
CLIENT_SECRET = 'G2B5HMMHBEVQ5QI2JDWXYFAG1U5I4NAA11KVNQBVSFC05GZG' 
ACCESS_TOKEN = 'VA0SECL4SPWWSDVJFMIJMEWRRRTKKCMX1XDDL0KUAF4OLISQ'
VERSION = '20180604'
LIMIT = 30
RADIUS = 500
T_url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    T_latitude, 
    T_longitude,
    VERSION, 
    RADIUS, 
    LIMIT)
tor_results = requests.get(T_url).json()
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 5JAXSZRX035SR2MBU3J3GHQY1EF0ZD5VVENVEY3UJ4OFO0U0
CLIENT_SECRET:G2B5HMMHBEVQ5QI2JDWXYFAG1U5I4NAA11KVNQBVSFC05GZG

In [196]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    
    for name, lat, lng in zip(names, latitudes, longitudes):

        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)

        results = requests.get(url).json()["response"]['groups'][0]['items']

        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])


    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [197]:
toronto_places = getNearbyVenues(names=T_df['Neighborhood'],
                                   latitudes=T_df['Latitude'],
                                   longitudes=T_df['Longitude']
                                  )

KeyError: 'groups'

In [ ]:
print(toronto_places.shape)
print("There are "+ str(len(toronto_places["Venue Category"].unique()))+" unique venue categories and "+ str(toronto_places["Venue"].count()) +" venues in Toronto")
toronto_places.head()

In [ ]:
print("There are a total of "+ str(len(toronto_places["Venue Category"].unique()))+" unique venue categories and "+ str(toronto_places["Venue"].count()) +" venues in Toronto")

### Comparing the two data sets

In [ ]:
set_toronto_places = set (toronto_places["Venue Category"])
set_NY_places = set (NY_places["Venue Category"])
set_common_places = set_NY_places.intersection(set_toronto_places)


common_places_count = len(set_common_places)
NY_unique = len(set_NY_places) - common_places_count
toronto_unique = len(set_toronto_places) - common_places_count
print("Toronto venues common to New York: {0} \nNew York unique venue that will be discarded: {1}\nToronto unique venues that will be discarded: {2}".format(common_places_count,NY_unique,toronto_unique))

In [ ]:
plt.figure(figsize = (10,10))
out = venn2(subsets = (set_toronto_places,set_NY_places), set_labels = ['Toronto city', 'New York'])
for text in out.set_labels:
    text.set_fontsize(18)
for text in out.subset_labels:
    text.set_fontsize(18)
plt.show()

In [ ]:
toronto_clean= toronto_places[toronto_places["Venue Category"].isin(set_common_places)]
NY_clean= NY_venues[ny_venues["Venue Category"].isin(set_common_places)]

print("Total venues in Toronto: {0}".format(toronto_clean.shape[0]))
print("Total venues in New York: {0}".format(NY_clean.shape[0]))